export interface MockFoodItem {
  id: string;
  name: string;
  category_id: string;
  price: number;
  rating: number;
  rating_count: number;
  preparation_time: number;
  restaurant_name: string;
  description: string;
  image: string;
  calories?: number;
  protein_g?: number;
  carbs_g?: number;
  available: boolean;
  is_popular: boolean;
  is_recommended: boolean;
}

export const MOCK_CATEGORIES = [
  { id: "mandi", name: "Mandi" },
  { id: "alfaham", name: "Al Faham" },
  { id: "shawarma", name: "Shawarma" },
  { id: "burger", name: "Burger" },
  { id: "drinks", name: "Drinks" },
  { id: "juices", name: "Juices" },
  { id: "shakes", name: "Shakes" },
  { id: "hot", name: "Hot" },
  { id: "lime", name: "Lime" },
  { id: "mojitos", name: "Mojitos" }
];

export const MOCK_FOOD_ITEMS: MockFoodItem[] = [
  {
    "id": "mandi-1",
    "name": "Al Faham Mandi Qtr",
    "category_id": "mandi",
    "price": 230,
    "rating": 4.7,
    "rating_count": 202,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Al Faham Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600",
    "calories": 879,
    "protein_g": 43,
    "carbs_g": 36,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-2",
    "name": "Al Faham Mandi Half",
    "category_id": "mandi",
    "price": 460,
    "rating": 4.5,
    "rating_count": 519,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Al Faham Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600",
    "calories": 846,
    "protein_g": 52,
    "carbs_g": 16,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-3",
    "name": "Al Faham Mandi Full",
    "category_id": "mandi",
    "price": 900,
    "rating": 4.7,
    "rating_count": 230,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Al Faham Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600",
    "calories": 515,
    "protein_g": 37,
    "carbs_g": 32,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-4",
    "name": "BBQ Mandi Qtr",
    "category_id": "mandi",
    "price": 240,
    "rating": 4.5,
    "rating_count": 208,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "BBQ Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600",
    "calories": 787,
    "protein_g": 41,
    "carbs_g": 88,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-5",
    "name": "BBQ Mandi Half",
    "category_id": "mandi",
    "price": 480,
    "rating": 4.8,
    "rating_count": 1818,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "BBQ Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600",
    "calories": 612,
    "protein_g": 49,
    "carbs_g": 80,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-6",
    "name": "BBQ Mandi Full",
    "category_id": "mandi",
    "price": 960,
    "rating": 4.5,
    "rating_count": 126,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "BBQ Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600",
    "calories": 888,
    "protein_g": 40,
    "carbs_g": 94,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-7",
    "name": "Beef Rib Mandi Qtr",
    "category_id": "mandi",
    "price": 280,
    "rating": 4.6,
    "rating_count": 1238,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Beef Rib Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=600",
    "calories": 579,
    "protein_g": 41,
    "carbs_g": 48,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-8",
    "name": "Beef Rib Mandi Half",
    "category_id": "mandi",
    "price": 560,
    "rating": 4.5,
    "rating_count": 1656,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Beef Rib Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=600",
    "calories": 549,
    "protein_g": 46,
    "carbs_g": 49,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-9",
    "name": "Beef Rib Mandi Full",
    "category_id": "mandi",
    "price": 1050,
    "rating": 4.7,
    "rating_count": 277,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Beef Rib Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=600",
    "calories": 873,
    "protein_g": 49,
    "carbs_g": 73,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-10",
    "name": "Chicken Mandi (Yemeni) Qtr",
    "category_id": "mandi",
    "price": 210,
    "rating": 4.5,
    "rating_count": 1650,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Chicken Mandi (Yemeni) Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600",
    "calories": 540,
    "protein_g": 52,
    "carbs_g": 42,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-11",
    "name": "Chicken Mandi (Yemeni) Half",
    "category_id": "mandi",
    "price": 410,
    "rating": 4.8,
    "rating_count": 1581,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Chicken Mandi (Yemeni) Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600",
    "calories": 795,
    "protein_g": 41,
    "carbs_g": 95,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-12",
    "name": "Chicken Mandi (Yemeni) Full",
    "category_id": "mandi",
    "price": 800,
    "rating": 4.4,
    "rating_count": 1033,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Chicken Mandi (Yemeni) Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "/images/yemeni_chicken_mandi.png",
    "calories": 895,
    "protein_g": 44,
    "carbs_g": 15,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "mandi-13",
    "name": "Honey Chilly Mandi Qtr",
    "category_id": "mandi",
    "price": 240,
    "rating": 4.8,
    "rating_count": 513,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Honey Chilly Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=600",
    "calories": 694,
    "protein_g": 43,
    "carbs_g": 63,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-14",
    "name": "Honey Chilly Mandi Half",
    "category_id": "mandi",
    "price": 480,
    "rating": 4.7,
    "rating_count": 1594,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Honey Chilly Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=600",
    "calories": 583,
    "protein_g": 46,
    "carbs_g": 50,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-15",
    "name": "Honey Chilly Mandi Full",
    "category_id": "mandi",
    "price": 960,
    "rating": 4.5,
    "rating_count": 1193,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Honey Chilly Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=600",
    "calories": 859,
    "protein_g": 55,
    "carbs_g": 14,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-16",
    "name": "Kanthari Mandi Qtr",
    "category_id": "mandi",
    "price": 240,
    "rating": 4.7,
    "rating_count": 800,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Kanthari Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600",
    "calories": 773,
    "protein_g": 42,
    "carbs_g": 25,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-17",
    "name": "Kanthari Mandi Half",
    "category_id": "mandi",
    "price": 480,
    "rating": 4.6,
    "rating_count": 1205,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Kanthari Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600",
    "calories": 827,
    "protein_g": 52,
    "carbs_g": 33,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-18",
    "name": "Kanthari Mandi Full",
    "category_id": "mandi",
    "price": 960,
    "rating": 4.7,
    "rating_count": 329,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Kanthari Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600",
    "calories": 617,
    "protein_g": 36,
    "carbs_g": 45,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-19",
    "name": "Masala Shawai Mandi Qtr",
    "category_id": "mandi",
    "price": 250,
    "rating": 4.6,
    "rating_count": 371,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Masala Shawai Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1621979087325-2273e7569178?w=600",
    "calories": 608,
    "protein_g": 53,
    "carbs_g": 45,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-20",
    "name": "Masala Shawai Mandi Half",
    "category_id": "mandi",
    "price": 500,
    "rating": 4.5,
    "rating_count": 2144,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Masala Shawai Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1621979087325-2273e7569178?w=600",
    "calories": 702,
    "protein_g": 55,
    "carbs_g": 63,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-21",
    "name": "Masala Shawai Mandi Full",
    "category_id": "mandi",
    "price": 980,
    "rating": 4.5,
    "rating_count": 671,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Masala Shawai Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1621979087325-2273e7569178?w=600",
    "calories": 626,
    "protein_g": 52,
    "carbs_g": 73,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-22",
    "name": "Peri Peri Mandi Qtr",
    "category_id": "mandi",
    "price": 240,
    "rating": 4.5,
    "rating_count": 2494,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Peri Peri Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1626776878345-5d9c220f8623?w=600",
    "calories": 719,
    "protein_g": 53,
    "carbs_g": 56,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-23",
    "name": "Peri Peri Mandi Half",
    "category_id": "mandi",
    "price": 480,
    "rating": 4.6,
    "rating_count": 666,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Peri Peri Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1626776878345-5d9c220f8623?w=600",
    "calories": 760,
    "protein_g": 50,
    "carbs_g": 16,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-24",
    "name": "Peri Peri Mandi Full",
    "category_id": "mandi",
    "price": 960,
    "rating": 4.8,
    "rating_count": 549,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Peri Peri Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1626776878345-5d9c220f8623?w=600",
    "calories": 578,
    "protein_g": 55,
    "carbs_g": 25,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-25",
    "name": "Smoked Mandi Qtr",
    "category_id": "mandi",
    "price": 240,
    "rating": 4.8,
    "rating_count": 1829,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Smoked Mandi Qtr. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600",
    "calories": 805,
    "protein_g": 37,
    "carbs_g": 54,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-26",
    "name": "Smoked Mandi Half",
    "category_id": "mandi",
    "price": 480,
    "rating": 4.6,
    "rating_count": 2017,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Smoked Mandi Half. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600",
    "calories": 770,
    "protein_g": 43,
    "carbs_g": 75,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mandi-27",
    "name": "Smoked Mandi Full",
    "category_id": "mandi",
    "price": 960,
    "rating": 4.8,
    "rating_count": 147,
    "preparation_time": 30,
    "restaurant_name": "Arabian Nights Mandi",
    "description": "Smoked Mandi Full. Traditional fragrant basmati rice cooked with slow-cooked meats, topped with nuts and raisins, served with spicy tomato salsa and garlic sauce.",
    "image": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600",
    "calories": 848,
    "protein_g": 38,
    "carbs_g": 92,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-28",
    "name": "Honey Glazed Piece",
    "category_id": "alfaham",
    "price": 150,
    "rating": 4.8,
    "rating_count": 1192,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Honey Glazed Piece. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600",
    "calories": 893,
    "protein_g": 55,
    "carbs_g": 48,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-29",
    "name": "Honey Glazed Qtr",
    "category_id": "alfaham",
    "price": 160,
    "rating": 4.5,
    "rating_count": 1880,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Honey Glazed Qtr. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600",
    "calories": 580,
    "protein_g": 49,
    "carbs_g": 5,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-30",
    "name": "Kanthari Al Faham Qtr",
    "category_id": "alfaham",
    "price": 160,
    "rating": 4.9,
    "rating_count": 1178,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Kanthari Al Faham Qtr. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600",
    "calories": 756,
    "protein_g": 40,
    "carbs_g": 69,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-31",
    "name": "Kanthari Al Faham Half",
    "category_id": "alfaham",
    "price": 320,
    "rating": 4.9,
    "rating_count": 1322,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Kanthari Al Faham Half. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "/images/kanthari_al_faham.png",
    "calories": 930,
    "protein_g": 55,
    "carbs_g": 69,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "alfaham-32",
    "name": "Kanthari Al Faham Full",
    "category_id": "alfaham",
    "price": 640,
    "rating": 4.7,
    "rating_count": 726,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Kanthari Al Faham Full. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "/images/kanthari_al_faham.png",
    "calories": 691,
    "protein_g": 40,
    "carbs_g": 74,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "alfaham-33",
    "name": "Lucka Shawaya Piece",
    "category_id": "alfaham",
    "price": 150,
    "rating": 4.9,
    "rating_count": 2272,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Lucka Shawaya Piece. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600",
    "calories": 500,
    "protein_g": 54,
    "carbs_g": 46,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-34",
    "name": "Lucka Shawaya Grilled Qtr",
    "category_id": "alfaham",
    "price": 160,
    "rating": 4.6,
    "rating_count": 558,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Lucka Shawaya Grilled Qtr. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600",
    "calories": 685,
    "protein_g": 44,
    "carbs_g": 35,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-35",
    "name": "Lucka Shawaya Grilled Half",
    "category_id": "alfaham",
    "price": 320,
    "rating": 4.4,
    "rating_count": 2423,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Lucka Shawaya Grilled Half. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600",
    "calories": 540,
    "protein_g": 37,
    "carbs_g": 67,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-36",
    "name": "Lucka Shawaya Grilled Full",
    "category_id": "alfaham",
    "price": 640,
    "rating": 4.8,
    "rating_count": 2281,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Lucka Shawaya Grilled Full. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600",
    "calories": 892,
    "protein_g": 39,
    "carbs_g": 21,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-37",
    "name": "Masala Shawaya Piece",
    "category_id": "alfaham",
    "price": 150,
    "rating": 4.7,
    "rating_count": 2351,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Masala Shawaya Piece. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1598515214211-89d3e73ae83b?w=600",
    "calories": 584,
    "protein_g": 43,
    "carbs_g": 72,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-38",
    "name": "Masala Shawaya Grilled Qtr",
    "category_id": "alfaham",
    "price": 160,
    "rating": 4.8,
    "rating_count": 1833,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Masala Shawaya Grilled Qtr. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1598515214211-89d3e73ae83b?w=600",
    "calories": 608,
    "protein_g": 52,
    "carbs_g": 93,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-39",
    "name": "Masala Shawaya Grilled Half",
    "category_id": "alfaham",
    "price": 320,
    "rating": 4.5,
    "rating_count": 1376,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Masala Shawaya Grilled Half. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1598515214211-89d3e73ae83b?w=600",
    "calories": 704,
    "protein_g": 55,
    "carbs_g": 52,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-40",
    "name": "Masala Shawaya Grilled Full",
    "category_id": "alfaham",
    "price": 640,
    "rating": 4.6,
    "rating_count": 2219,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Masala Shawaya Grilled Full. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1598515214211-89d3e73ae83b?w=600",
    "calories": 731,
    "protein_g": 38,
    "carbs_g": 36,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-41",
    "name": "Mexican Al Faham Piece",
    "category_id": "alfaham",
    "price": 140,
    "rating": 4.5,
    "rating_count": 1484,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Mexican Al Faham Piece. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600",
    "calories": 510,
    "protein_g": 53,
    "carbs_g": 75,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-42",
    "name": "Mexican Al Faham Qtr",
    "category_id": "alfaham",
    "price": 150,
    "rating": 4.5,
    "rating_count": 1002,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Mexican Al Faham Qtr. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600",
    "calories": 503,
    "protein_g": 37,
    "carbs_g": 95,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-43",
    "name": "Mexican Al Faham Half",
    "category_id": "alfaham",
    "price": 300,
    "rating": 4.7,
    "rating_count": 1037,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Mexican Al Faham Half. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600",
    "calories": 534,
    "protein_g": 36,
    "carbs_g": 47,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-44",
    "name": "Mexican Al Faham Full",
    "category_id": "alfaham",
    "price": 600,
    "rating": 4.4,
    "rating_count": 1074,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Mexican Al Faham Full. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600",
    "calories": 642,
    "protein_g": 50,
    "carbs_g": 32,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-45",
    "name": "Pepper Al Faham Full",
    "category_id": "alfaham",
    "price": 640,
    "rating": 4.7,
    "rating_count": 2438,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Pepper Al Faham Full. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600",
    "calories": 795,
    "protein_g": 50,
    "carbs_g": 36,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "alfaham-46",
    "name": "Mutton Piece",
    "category_id": "alfaham",
    "price": 270,
    "rating": 4.8,
    "rating_count": 1767,
    "preparation_time": 25,
    "restaurant_name": "GrillGo Charcoal & Al Faham",
    "description": "Mutton Piece. Juicy pieces of chicken/mutton marinated in fresh Arabic spices and yogurt, grilled to perfection over charcoal.",
    "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=600",
    "calories": 597,
    "protein_g": 38,
    "carbs_g": 17,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-47",
    "name": "Soda Bottle",
    "category_id": "drinks",
    "price": 10,
    "rating": 4.7,
    "rating_count": 1551,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Soda Bottle. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-48",
    "name": "Soda 600ml",
    "category_id": "drinks",
    "price": 20,
    "rating": 4.6,
    "rating_count": 2012,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Soda 600ml. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-49",
    "name": "Soda 2L",
    "category_id": "drinks",
    "price": 35,
    "rating": 4.8,
    "rating_count": 321,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Soda 2L. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-50",
    "name": "Soft Drink",
    "category_id": "drinks",
    "price": 40,
    "rating": 4.7,
    "rating_count": 503,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Soft Drink. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-51",
    "name": "Seven Up Can",
    "category_id": "drinks",
    "price": 40,
    "rating": 4.4,
    "rating_count": 1489,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Seven Up Can. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "/images/seven_up_soda.png",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "drinks-52",
    "name": "Seven Up 600ml",
    "category_id": "drinks",
    "price": 40,
    "rating": 4.8,
    "rating_count": 547,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Seven Up 600ml. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1567103472667-6898f3a83fe2?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-53",
    "name": "Seven Up 2L",
    "category_id": "drinks",
    "price": 100,
    "rating": 4.5,
    "rating_count": 879,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Seven Up 2L. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1567103472667-6898f3a83fe2?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-54",
    "name": "Sprite 250ml",
    "category_id": "drinks",
    "price": 20,
    "rating": 4.7,
    "rating_count": 674,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Sprite 250ml. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-55",
    "name": "Sprite 750ml",
    "category_id": "drinks",
    "price": 35,
    "rating": 4.6,
    "rating_count": 1240,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Sprite 750ml. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-56",
    "name": "Sprite 1L",
    "category_id": "drinks",
    "price": 50,
    "rating": 4.6,
    "rating_count": 408,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Sprite 1L. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "drinks-57",
    "name": "Sprite 2L",
    "category_id": "drinks",
    "price": 100,
    "rating": 4.6,
    "rating_count": 2354,
    "preparation_time": 5,
    "restaurant_name": "Beverage Hub",
    "description": "Sprite 2L. Chilled beverage bottle or can to perfectly complement your spicy grilled meal.",
    "image": "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-58",
    "name": "Apple Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.4,
    "rating_count": 2314,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Apple Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-59",
    "name": "Avocado Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.8,
    "rating_count": 482,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Avocado Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1550507992-eb63ffee0847?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-60",
    "name": "Butter Scotch Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.9,
    "rating_count": 1068,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Butter Scotch Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-61",
    "name": "Chikku Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.5,
    "rating_count": 2089,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Chikku Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1502741224143-90386d7c8c82?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-62",
    "name": "Chocolate Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.6,
    "rating_count": 1742,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Chocolate Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-63",
    "name": "Custard Apple Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.9,
    "rating_count": 774,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Custard Apple Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-64",
    "name": "Dates Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.6,
    "rating_count": 1699,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Dates Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1596450514735-111a2fe02935?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-65",
    "name": "Dates & Nuts Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.5,
    "rating_count": 1963,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Dates & Nuts Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1596450514735-111a2fe02935?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-66",
    "name": "Dry Fruits Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.5,
    "rating_count": 2376,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Dry Fruits Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-67",
    "name": "Fig Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.7,
    "rating_count": 2093,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Fig Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1596450514735-111a2fe02935?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-68",
    "name": "Guava Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.5,
    "rating_count": 1315,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Guava Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-69",
    "name": "Kit Kat Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.5,
    "rating_count": 339,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Kit Kat Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shakes-70",
    "name": "Mango Shake",
    "category_id": "shakes",
    "price": 80,
    "rating": 4.7,
    "rating_count": 2320,
    "preparation_time": 15,
    "restaurant_name": "Juice Corner & Shakes",
    "description": "Mango Shake. Thick and creamy rich milkshake prepared with fresh fruits, milk, vanilla ice cream, and dry fruits.",
    "image": "/images/mango_milkshake.png",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "juices-71",
    "name": "Orange Juice",
    "category_id": "juices",
    "price": 60,
    "rating": 4.4,
    "rating_count": 1384,
    "preparation_time": 10,
    "restaurant_name": "Juice Corner",
    "description": "Orange Juice. 100% natural, freshly squeezed cold juice. Extremely refreshing and nutritious.",
    "image": "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "juices-72",
    "name": "Pineapple Juice",
    "category_id": "juices",
    "price": 60,
    "rating": 4.4,
    "rating_count": 2492,
    "preparation_time": 10,
    "restaurant_name": "Juice Corner",
    "description": "Pineapple Juice. 100% natural, freshly squeezed cold juice. Extremely refreshing and nutritious.",
    "image": "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "juices-73",
    "name": "Watermelon Juice",
    "category_id": "juices",
    "price": 60,
    "rating": 4.6,
    "rating_count": 2275,
    "preparation_time": 10,
    "restaurant_name": "Juice Corner",
    "description": "Watermelon Juice. 100% natural, freshly squeezed cold juice. Extremely refreshing and nutritious.",
    "image": "/images/watermelon_juice.png",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "juices-74",
    "name": "Orange Lime",
    "category_id": "juices",
    "price": 30,
    "rating": 4.5,
    "rating_count": 2180,
    "preparation_time": 10,
    "restaurant_name": "Juice Corner",
    "description": "Orange Lime. 100% natural, freshly squeezed cold juice. Extremely refreshing and nutritious.",
    "image": "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "hot-75",
    "name": "Sulaimani",
    "category_id": "hot",
    "price": 10,
    "rating": 4.4,
    "rating_count": 861,
    "preparation_time": 8,
    "restaurant_name": "Hot Sips",
    "description": "Sulaimani. Freshly brewed warm and soothing beverage. Perfect finish to a heavy meal.",
    "image": "/images/sulaimani_tea.png",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "hot-76",
    "name": "Lime Tea",
    "category_id": "hot",
    "price": 15,
    "rating": 4.4,
    "rating_count": 378,
    "preparation_time": 8,
    "restaurant_name": "Hot Sips",
    "description": "Lime Tea. Freshly brewed warm and soothing beverage. Perfect finish to a heavy meal.",
    "image": "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "lime-77",
    "name": "Fresh Lime",
    "category_id": "lime",
    "price": 25,
    "rating": 4.7,
    "rating_count": 1063,
    "preparation_time": 8,
    "restaurant_name": "Juice Corner",
    "description": "Fresh Lime. Fizzy lime beverage prepared sweet or salted with fresh hand-pressed local limes.",
    "image": "https://images.unsplash.com/photo-1556881286-fc6915169721?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "lime-78",
    "name": "Ginger Lime",
    "category_id": "lime",
    "price": 30,
    "rating": 4.6,
    "rating_count": 2433,
    "preparation_time": 8,
    "restaurant_name": "Juice Corner",
    "description": "Ginger Lime. Fizzy lime beverage prepared sweet or salted with fresh hand-pressed local limes.",
    "image": "https://images.unsplash.com/photo-1603569283847-be40d7f3c09e?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "lime-79",
    "name": "Grape Lime",
    "category_id": "lime",
    "price": 30,
    "rating": 4.5,
    "rating_count": 262,
    "preparation_time": 8,
    "restaurant_name": "Juice Corner",
    "description": "Grape Lime. Fizzy lime beverage prepared sweet or salted with fresh hand-pressed local limes.",
    "image": "https://images.unsplash.com/photo-1508885368104-a4871600f1e0?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "lime-80",
    "name": "Mint Lime",
    "category_id": "lime",
    "price": 30,
    "rating": 4.7,
    "rating_count": 1817,
    "preparation_time": 8,
    "restaurant_name": "Juice Corner",
    "description": "Mint Lime. Fizzy lime beverage prepared sweet or salted with fresh hand-pressed local limes.",
    "image": "/images/mint_lime_drink.png",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "lime-81",
    "name": "Pineapple Lime",
    "category_id": "lime",
    "price": 30,
    "rating": 4.7,
    "rating_count": 2415,
    "preparation_time": 8,
    "restaurant_name": "Juice Corner",
    "description": "Pineapple Lime. Fizzy lime beverage prepared sweet or salted with fresh hand-pressed local limes.",
    "image": "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "lime-82",
    "name": "Soda Lime",
    "category_id": "lime",
    "price": 30,
    "rating": 4.7,
    "rating_count": 1168,
    "preparation_time": 8,
    "restaurant_name": "Juice Corner",
    "description": "Soda Lime. Fizzy lime beverage prepared sweet or salted with fresh hand-pressed local limes.",
    "image": "https://images.unsplash.com/photo-1556881286-fc6915169721?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-83",
    "name": "Blue Berry Mojito",
    "category_id": "mojitos",
    "price": 80,
    "rating": 4.5,
    "rating_count": 1386,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Blue Berry Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "/images/blue_curacao_mojito.png",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "mojitos-84",
    "name": "Blue Curacao Mojito",
    "category_id": "mojitos",
    "price": 80,
    "rating": 4.5,
    "rating_count": 1721,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Blue Curacao Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "/images/blue_curacao_mojito.png",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "mojitos-85",
    "name": "Green Apple Mojito",
    "category_id": "mojitos",
    "price": 80,
    "rating": 4.5,
    "rating_count": 1328,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Green Apple Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-86",
    "name": "Guava Mojito",
    "category_id": "mojitos",
    "price": 70,
    "rating": 4.6,
    "rating_count": 397,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Guava Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1497534446932-c925b458314e?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-87",
    "name": "Kacha Mango Mojito",
    "category_id": "mojitos",
    "price": 70,
    "rating": 4.4,
    "rating_count": 2406,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Kacha Mango Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-88",
    "name": "Litchi Mojito",
    "category_id": "mojitos",
    "price": 80,
    "rating": 4.9,
    "rating_count": 400,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Litchi Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-89",
    "name": "Mint Mojito",
    "category_id": "mojitos",
    "price": 70,
    "rating": 4.7,
    "rating_count": 2172,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Mint Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-90",
    "name": "Orange Mojito",
    "category_id": "mojitos",
    "price": 70,
    "rating": 4.5,
    "rating_count": 1529,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Orange Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-91",
    "name": "Passion Fruit Mojito",
    "category_id": "mojitos",
    "price": 70,
    "rating": 4.8,
    "rating_count": 1100,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Passion Fruit Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1575444758702-4a6b9222336e?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-92",
    "name": "Pineapple Mojito",
    "category_id": "mojitos",
    "price": 80,
    "rating": 4.6,
    "rating_count": 746,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Pineapple Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "mojitos-93",
    "name": "Pizza Mojito",
    "category_id": "mojitos",
    "price": 80,
    "rating": 4.6,
    "rating_count": 2325,
    "preparation_time": 12,
    "restaurant_name": "Mojito Lounge",
    "description": "Pizza Mojito. Chilled, bubbly mocktail made with fresh muddled mint leaves, lime wedges, signature syrup, and sparkling soda.",
    "image": "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=600",
    "calories": null,
    "protein_g": null,
    "carbs_g": null,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "shawarma-s1",
    "name": "Chicken Shawarma Roll",
    "category_id": "shawarma",
    "price": 120,
    "rating": 4.7,
    "rating_count": 1850,
    "preparation_time": 15,
    "restaurant_name": "Shawarma Express",
    "description": "Tender shredded chicken marinated in shawarma spice blend, wrapped in soft kubbus bread with pickled vegetables and homemade garlic mayonnaise.",
    "image": "/images/chicken_shawarma_roll.png",
    "calories": 450,
    "protein_g": 28,
    "carbs_g": 35,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "shawarma-s2",
    "name": "Plate Shawarma Special",
    "category_id": "shawarma",
    "price": 160,
    "rating": 4.8,
    "rating_count": 1200,
    "preparation_time": 15,
    "restaurant_name": "Shawarma Express",
    "description": "A generous serving of grilled shawarma chicken served on a plate with fresh tabbouleh, pickles, french fries, and premium garlic dip.",
    "image": "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600",
    "calories": 550,
    "protein_g": 34,
    "carbs_g": 40,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  },
  {
    "id": "burger-b1",
    "name": "Classic Beef Burger",
    "category_id": "burger",
    "price": 180,
    "rating": 4.6,
    "rating_count": 940,
    "preparation_time": 20,
    "restaurant_name": "GrillGo Burgers",
    "description": "Premium beef patty grilled to perfection, topped with melted cheddar, crisp lettuce, red onions, and our signature burger sauce on toasted brioche buns.",
    "image": "/images/classic_beef_burger.png",
    "calories": 580,
    "protein_g": 32,
    "carbs_g": 40,
    "available": true,
    "is_popular": true,
    "is_recommended": true
  },
  {
    "id": "burger-b2",
    "name": "Crispy Chicken Burger",
    "category_id": "burger",
    "price": 160,
    "rating": 4.7,
    "rating_count": 1450,
    "preparation_time": 20,
    "restaurant_name": "GrillGo Burgers",
    "description": "Buttermilk-fried crispy chicken breast fillet topped with spicy mayo, crunchy lettuce, and sliced gherkins on sesame seed buns.",
    "image": "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600",
    "calories": 540,
    "protein_g": 28,
    "carbs_g": 42,
    "available": true,
    "is_popular": true,
    "is_recommended": false
  }
];
